### PR TITLE
add nuxui

### PR DESCRIPTION
**Pull request by nuxart**

### CODE REVIEW

**Review by go101 — APPROVED** [review]
@nuxart 
Thanks for the suggestion.

I think this tool should be categorized into the "native GUI and utility bindings" section.
So I will merge this PR firstly then move the link to that section.

If you have different opinion, you can leave a comment here.

**Comment by go101** [comment]
Aha, sorry, it looks you put it exactly in that section. So I just moved it according to the alphabet.

**Comment by go101** [comment]
BTW, it is a tool looking quite promising.

**Comment by go101** [comment]
BTW, it is a tool looking quite promising.

**Comment by nuxart** [comment]
Thanks

**Pull request merged**
